import "./globals.css";
import type { Metadata } from "next";
import MainLayout from "@/components/layouts/MainLayout";

export const metadata: Metadata = {
  title: "itoll task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <MainLayout>{children}</MainLayout>;
}
